### PR TITLE
Fixed resource leak in sootup.java.bytecode.frontend module

### LINKED ISSUE #1032: [Bug]: Resource leaks detected in sootup.java.bytecode and sootup.core module
### What happened?

Ran the [Resource Leak Checker](https://checkerframework.org/manual/#resource-leak-checker) and detected various resource leaks in both sootup.java.bytecode and sootup.core module.

### Version

Latest develop branch

### Relevant log output

```shell
sootup.core/src/main/java/sootup/core/util/Utils.java:[105,30] 
error: [required.method.not.called] @MustCall method close may not have been invoked on fileManager or any of its aliases.
[ERROR]   The type of object is: javax.tools.StandardJavaFileManager.
[ERROR]   Reason for going out of scope: possible exceptional exit due to throw new IllegalArgumentException("could not compile source file."); with exception type java.lang.IllegalArgumentException

sootup.java.bytecode/src/main/java/sootup/java/bytecode/inputlocation/MultiReleaseJarAnalysisInputLocation.java:[209,22] error: [required.method.not.called] @MustCall method close may not have been invoked on inputStream or any of its aliases.
[ERROR]   The type of object is: java.io.FileInputStream.
[ERROR]   Reason for going out of scope: possible exceptional exit due to new JarInputStream(inputStream) with exception type java.io.IOException

sootup.java.bytecode/src/main/java/sootup/java/bytecode/inputlocation/PathBasedAnalysisInputLocation.java:[378,20] error: [required.method.not.called] @MustCall method close may not have been invoked on Files.walk(libDir) or any of its aliases.
[ERROR]   The type of object is: java.util.stream.Stream<java.nio.file.Path>.
[ERROR]   Reason for going out of scope: regular method exit

sootup.java.bytecode/src/main/java/sootup/java/bytecode/inputlocation/PathBasedAnalysisInputLocation.java:[445,68] error: [required.method.not.called] @MustCall method close may not have been invoked on Files.newInputStream(warFilePath) or any of its aliases.
[ERROR]   The type of object is: java.io.InputStream.
[ERROR]   Reason for going out of scope: possible exceptional exit due to zis.getNextEntry() with exception type java.io.IOException

sootup.java.bytecode/src/main/java/sootup/java/bytecode/inputlocation/PathBasedAnalysisInputLocation.java:[461,62] error: [required.method.not.called] @MustCall method close may not have been invoked on Files.newInputStream(file.toPath()) or any of its aliases.
[ERROR]   The type of object is: java.io.InputStream.
[ERROR]   Reason for going out of scope: possible exceptional exit due to zis.read(incomingValues) with exception type java.io.IOException

sootup.java.bytecode/src/main/java/sootup/java/bytecode/inputlocation/PathBasedAnalysisInputLocation.java:[487,64] error: [required.method.not.called] @MustCall method close may not have been invoked on Files.newOutputStream(file.toPath()) or any of its aliases.
[ERROR]   The type of object is: java.io.OutputStream.
[ERROR]   Reason for going out of scope: possible exceptional exit due to zis.read(incomingValues) with exception type java.io.IOException

sootup.java.bytecode/src/main/java/sootup/java/bytecode/inputlocation/OTFCompileAnalysisInputLocation.java:[182,30] error: [required.method.not.called] @MustCall method close may not have been invoked on fileManager or any of its aliases.
[ERROR]   The type of object is: javax.tools.StandardJavaFileManager.
[ERROR]   Reason for going out of scope: possible exceptional exit due to fileManager.setLocation(StandardLocation.CLASS_OUTPUT, Collections.singleton(binDir)) with exception type java.io.IOException

sootup.java.bytecode/src/main/java/sootup/java/bytecode/inputlocation/ModuleFinder.java:[283,14] error: [required.method.not.called] @MustCall method close may not have been invoked on jar or any of its aliases.
[ERROR]   The type of object is: java.util.jar.JarFile.
[ERROR]   Reason for going out of scope: regular method exit

sootup.java.bytecode/src/main/java/sootup/java/bytecode/inputlocation/ModuleFinder.java:[288,59] error: [required.method.not.called] @MustCall method close may not have been invoked on jar.getInputStream(entry) or any of its aliases.
[ERROR]   The type of object is: java.io.InputStream.
[ERROR]   Reason for going out of scope: possible exceptional exit due to new Manifest(jar.getInputStream(entry)) with exception type java.io.IOException
```

### LINKED ISSUE #1098: [Bug]: Resource Leak detected in sootup.java.bytecode.frontend module
### What happened?

Ran the [Resource Leak Checker](https://checkerframework.org/manual/#resource-leak-checker) and detected a resource leak in sootup.java.bytecode.frontend module.

### Version

Latest develop branch

### Relevant log output

```shell
sootup.java.bytecode.frontend/src/main/java/sootup/java/bytecode/frontend/inputlocation/JrtFileSystemAnalysisInputLocation.java:[154,23] error: [required.method.not.called] @MustCall method close may not have been invoked on Files.walk(archiveRoot) or any of its aliases.
[ERROR]   The type of object is: java.util.stream.Stream<java.nio.file.Path>.
[ERROR]   Reason for going out of scope: regular method exit
```

### PR DESCRIPTION
**Pull request by Bryce7832**
Fixed leak using try-with-resources. However, changed the method to return a ```List``` and do the ```collect``` operation inside the method to avoid try-with-resources closing the stream before its last use. This ensures the resources to be cleaned up. Fixes #1098

### CODE REVIEW

File: sootup.java.bytecode.frontend/src/main/java/sootup/java/bytecode/frontend/inputlocation/JrtFileSystemAnalysisInputLocation.java [hunk 1]
```diff
@@ -149,21 +150,25 @@ protected Stream<JavaSootClassSource> getClassSourcesInternal(
...
+                              .toString()
+                              .endsWith(classProvider.getHandledFileType().getExtensionWithDot())
+                          && !filePath.toString().endsWith(moduleInfoFilename))
+              .<SootClassSource>flatMap(
+                  p ->
+                      StreamUtils.optionalToStream(
+                          classProvider.createClassSource(this, p, fromPath(p, identifierFactory))))
+              .map(src -> (JavaSootClassSource) src)
+              .collect(Collectors.toList());
+      return javaSootClassSources.stream();
```
Comment (swissiety) [inline sootup.java.bytecode.frontend/src/main/java/sootup/java/bytecode/frontend/inputlocation/JrtFileSystemAnalysisInputLocation.java:174]: please don' t .collect() and .stream() again (return  stream directly)

**Review by swissiety — CHANGES_REQUESTED** [review]
thx for your contribution!

File: sootup.java.bytecode.frontend/src/main/java/sootup/java/bytecode/frontend/inputlocation/JrtFileSystemAnalysisInputLocation.java (hunk 1 above)
Comment (msridhar) [reply sootup.java.bytecode.frontend/src/main/java/sootup/java/bytecode/frontend/inputlocation/JrtFileSystemAnalysisInputLocation.java:174]: Hi @swissiety since streams are lazy, if we don't collect, we cannot safely close the `Stream` returned by `Files.walk` within this method (since the filter and map operations won't have been executed yet).  The `collect` forces those operations to execute, so then the stream can be closed.  If you prefer not to collect and then stream again, an alternative would be to require all callers of this method to close the returned stream.  Would that be preferable?

Comment (swissiety) [reply sootup.java.bytecode.frontend/src/main/java/sootup/java/bytecode/frontend/inputlocation/JrtFileSystemAnalysisInputLocation.java:174]: thx @msridhar for pointing to that situation! As this is a protected method and its calling contexts are collecting the Stream again i would prefer to close the Stream in the two calling method(s) due to have less allocations

Comment (msridhar) [reply sootup.java.bytecode.frontend/src/main/java/sootup/java/bytecode/frontend/inputlocation/JrtFileSystemAnalysisInputLocation.java:174]: @Bryce7832 could you update the PR to get rid of the collect to a list, and instead use try-with-resources at both callers of this method?

**Review by swissiety — APPROVED** [review]
