### PR TITLE
issue-982 : Assign TopType to ObjectType at end of TypeAssigner

### LINKED ISSUE #982: [Bug]: TypeAssigner fails if LocalSplitter is not applied beforehand
### What happened?

When using the TypeAssigner without the LocalSplitter there are some cases where the TypeAssigner assignes `BottomType` or `TopType`. Make the TypeAssigner not assign any type in such cases to not break the Jimple. 

### Version

Latest develop branch

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by sahilagichani14**
assign TopType to ObjectType at the end of TypeAssigner so LocalNameStandardizer doesn't give exception after.

### CODE REVIEW

File: shared-test-resources/TypeResolverTestSuite/Misc/Misc.java [hunk 1]
```diff
@@ -70,6 +72,35 @@ public static void impossibleTyping() {
...
 
+  public static void testTaAndLnsWithoutLS() {
+    int a = 10, c;
+    try {
+      a = 8 / 0;
+      int b = a + 2;
+      c = a;
+    } catch (ArithmeticException ex) {
+    }
+    System.out.println(a);
```
Comment (JonasKlauke) [inline shared-test-resources/TypeResolverTestSuite/Misc/Misc.java]: remove println from the testcases. It unnecessary blows up the tests

File: shared-test-resources/TypeResolverTestSuite/Misc/io/jsonwebtoken/impl/lang/JwtDateConverter.class
Comment (stschott) [inline shared-test-resources/TypeResolverTestSuite/Misc/io/jsonwebtoken/impl/lang/JwtDateConverter.class:1]: Please isolate the issue and provide a source/class file pair instead of a class from a different library.

**Review by stschott — CHANGES_REQUESTED** [review]

File: shared-test-resources/TypeResolverTestSuite/Misc/io/jsonwebtoken/impl/lang/JwtDateConverter.class
Comment (sahilagichani14) [reply shared-test-resources/TypeResolverTestSuite/Misc/io/jsonwebtoken/impl/lang/JwtDateConverter.class:1]: I have added that test case as well, I will remove this class from a diff lib.

**Review by stschott — APPROVED** [review]
