### PR TITLE
Issue 988 type assigner warning if no rt.jar found

### LINKED ISSUE #988: [Bug]: java.lang.IllegalStateException: Failed to apply sootup.java.core.interceptors.TypeAssigner
### What happened?

when running the mockito-core-5.3.1.jar, or logback-core-1.4.7.jar with java 8 version but without DefaultRTJarAnalysisInputLocation() in input location, fails at "The path from 'java.lang.RuntimeException' to java.lang.Throwable cannot be found!"

### Version

Latest develop branch

### Relevant log output

```shell
java.lang.IllegalStateException: Failed to apply sootup.java.core.interceptors.TypeAssigner@550fe9d7 to <org.mockito.internal.MockedStaticImpl: void verify(org.mockito.MockedStatic$Verification,org.mockito.verification.VerificationMode)>

	at sootup.java.bytecode.frontend.AsmMethodSource.resolveBody(AsmMethodSource.java:240)
	at sootup.core.model.SootMethod.lazyBodyInitializer(SootMethod.java:98)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
	at sootup.core.model.SootMethod.getBody(SootMethod.java:177)
	at sootup.java.bytecode.interceptors.typeresolving.TypeResolverTest.applyTrToJar(TypeResolverTest.java:351)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at sootup.java.bytecode.interceptors.typeresolving.TypeResolverTest.testTrWithoutLs(TypeResolverTest.java:292)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
Caused by: java.lang.IllegalStateException: The path from 'java.lang.RuntimeException' to java.lang.Throwable cannot be found!
	at sootup.java.core.interceptors.typeresolving.AugEvalFunction.getExceptionPath(AugEvalFunction.java:252)
	at sootup.java.core.interceptors.typeresolving.AugEvalFunction.getLeastCommonExceptionType(AugEvalFunction.java:274)
	at sootup.java.core.interceptors.typeresolving.AugEvalFunction.evaluate(AugEvalFunction.java:195)
	at sootup.java.core.interceptors.typeresolving.TypeResolver.applyAssignmentConstraint(TypeResolver.java:215)
	at sootup.java.core.interceptors.typeresolving.TypeResolver.resolve(TypeResolver.java:74)
	at sootup.java.core.interceptors.TypeAssigner.interceptBody(TypeAssigner.java:42)
	at sootup.java.bytecode.frontend.AsmMethodSource.resolveBody(AsmMethodSource.java:234)
	... 9 more
```

### PR DESCRIPTION
**Pull request by sahilagichani14**

### CODE REVIEW

**Comment by sahilagichani14** [comment]
This is the case when running type assigner without rt.jar and reaching a situation where no SuperClass of exception class could be found. So warn about no rt.jar present

**Comment by sahilagichani14** [comment]
dependent on the bug fix, issue-975-typeresolver. once issue fix 975 is merged this would also pass

File: sootup.java.bytecode/src/test/java/sootup/java/bytecode/interceptors/typeresolving/TypeResolverTest.java [hunk 1]
```diff
@@ -294,6 +293,39 @@ public void testStringDefaultMethodsTest() {
...
   }
 
+  @Test
+  public void testTAWarningWithoutRTJar() {
+    String directoryPath = baseDir + "Misc/";
+    try {
+      List<String> jarFileNames = listJarFiles(directoryPath);
+      jarFileNames.forEach(
+          jarFile -> {
+            System.out.println("Applying Type Assigner to jar " + jarFile);
```
Comment (JonasKlauke) [inline sootup.java.bytecode/src/test/java/sootup/java/bytecode/interceptors/typeresolving/TypeResolverTest.java]: remove the println from the test case

File: sootup.java.bytecode/src/test/java/sootup/java/bytecode/interceptors/typeresolving/TypeResolverTest.java [hunk 2]
```diff
@@ -294,6 +293,39 @@ public void testStringDefaultMethodsTest() {
...
+    }
+  }
+
+  public static List<String> listJarFiles(String directoryPath) throws IOException {
+    try (Stream<Path> paths = Files.walk(Paths.get(directoryPath))) {
+      return paths
+          .filter(Files::isRegularFile)
+          .filter(path -> path.toString().toLowerCase().endsWith(".jar"))
+          .sorted(
+              (path1, path2) -> {
```
Comment (JonasKlauke) [inline sootup.java.bytecode/src/test/java/sootup/java/bytecode/interceptors/typeresolving/TypeResolverTest.java]: is there a reason for sorting it?

File: sootup.java.bytecode/src/test/java/sootup/java/bytecode/interceptors/typeresolving/TypeResolverTest.java [hunk 3]
```diff
@@ -294,6 +293,39 @@ public void testStringDefaultMethodsTest() {
...
+          });
+    } catch (IOException e) {
+      e.printStackTrace();
+    }
+  }
+
+  public static List<String> listJarFiles(String directoryPath) throws IOException {
+    try (Stream<Path> paths = Files.walk(Paths.get(directoryPath))) {
+      return paths
+          .filter(Files::isRegularFile)
```
Comment (stschott) [inline sootup.java.bytecode/src/test/java/sootup/java/bytecode/interceptors/typeresolving/TypeResolverTest.java]: Can we, instead of using a jar for the test case, use a source/class file pair so that one can check the corresponding source?

**Review by stschott — CHANGES_REQUESTED** [review]

**Review by JonasKlauke — COMMENTED** [review]
mmh the testcase should test the warning, it should not be a visual test by the developer

File: sootup.java.bytecode/src/test/java/sootup/java/bytecode/interceptors/typeresolving/TypeResolverTest.java (hunk 2 above)
Comment (sahilagichani14) [reply sootup.java.bytecode/src/test/java/sootup/java/bytecode/interceptors/typeresolving/TypeResolverTest.java]: No, first I was testing 10 jars so I sorted them but now will remove it 👍

File: sootup.java.bytecode/src/test/java/sootup/java/bytecode/interceptors/typeresolving/TypeResolverTest.java (hunk 1 above)
Comment (sahilagichani14) [reply sootup.java.bytecode/src/test/java/sootup/java/bytecode/interceptors/typeresolving/TypeResolverTest.java]: @JonasKlauke Umm okay I will add Memory Appender for testing logs. 👍

**Review by stschott — APPROVED** [review]
