### PR TITLE
fix lns Interger1Type, Interger127Type, etc

### LINKED ISSUE #1080: [Bug]:  LocalNameStandardizer not handling Integer1Type, Integer127Type
### What happened?

when applying localSplitter, TypeAssigner, then LocalNameStandardiser. It fails as it doesn't handle Integer1Type, Integer127Type types etc.

### Version

Latest develop branch

### Relevant log output

```shell
Exception in thread "main" java.lang.IllegalStateException: Failed to apply sootup.core.transform.RunTimeBodyInterceptor@7ec4648f to <org.mockito.internal.reporting.SmartPrinter: boolean isMultiLine(org.mockito.invocation.MatchableInvocation,java.util.List)>
	at sootup.java.bytecode.frontend.conversion.AsmMethodSource.resolveBody(AsmMethodSource.java:241)
	at sootup.core.model.SootMethod.lazyBodyInitializer(SootMethod.java:98)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:200)
	at sootup.core.model.SootMethod.getBody(SootMethod.java:177)
	at upb.thesis.SetUp.lambda$1(SetUp.java:190)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at upb.thesis.SetUp.lambda$0(SetUp.java:188)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at upb.thesis.SetUp.setupSootUp(SetUp.java:187)
	at upb.thesis.SetUp.executeStaticAnalysis(SetUp.java:48)
	at upb.thesis.Main.main(Main.java:80)
Caused by: java.lang.UnsupportedOperationException
	at sootup.interceptors.typeresolving.types.AugmentIntegerTypes$Integer1Type.accept(AugmentIntegerTypes.java:63)
	at sootup.interceptors.typeresolving.types.AugmentIntegerTypes$Integer1Type.accept(AugmentIntegerTypes.java:49)
	at sootup.core.jimple.basic.LocalGenerator.generateLocal(LocalGenerator.java:68)
	at sootup.interceptors.LocalNameStandardizer.interceptBody(LocalNameStandardizer.java:77)
	at sootup.core.transform.RunTimeBodyInterceptor.interceptBody(RunTimeBodyInterceptor.java:54)
	at sootup.java.bytecode.frontend.conversion.AsmMethodSource.resolveBody(AsmMethodSource.java:235)
	... 18 more
```

### PR DESCRIPTION
**Pull request by sahilagichani14**
fix types created by type assigner, later using LocalNameStandardiser handle types such as TopType, Interger1Type, Interger127Type, etc.

### CODE REVIEW

**Review by swissiety — COMMENTED** [review]
these are leftovers from TypeAssigner which should not appear outside of it / in a StmtGraph

**Review by swissiety — APPROVED** [review]

File: sootup.interceptors/src/main/java/sootup/interceptors/LocalNameStandardizer.java [hunk 1]
```diff
@@ -31,7 +31,6 @@
 import sootup.core.transform.BodyInterceptor;
 import sootup.core.types.Type;
 import sootup.core.views.View;
-import sootup.interceptors.typeresolving.types.BottomType;
 
 // https://github.com/Sable/soot/blob/master/src/main/java/soot/jimple/toolkits/scalar/LocalNameStandardizer.java
```
Comment (swissiety) [inline sootup.interceptors/src/main/java/sootup/interceptors/LocalNameStandardizer.java]:
```suggestion
```
